---
- block:
  - name: Obtain Devportal pgmaster IP from inventory
    set_fact:
      cacheable: yes
      db_pgmaster_ip: "{{ hostvars[groups['dp-db-pgmaster'][0]][interface_name].ipv4.address }}"
    when: db_pgmaster_ip is not defined

  - name: Obtain Devportal pgstandby IP from inventory
    set_fact:
      cacheable: yes
      db_pgstandby_ip: "{{ hostvars[groups['dp-db-pgstandby'][0]][interface_name].ipv4.address }}"
    when: db_pgstandby_ip is not defined

  when: groups['dp-db-pgmaster'] is defined and groups['dp-db-pgstandby'] is defined and groups['dp-db-pgmaster'][0][interface_name] is defined and groups['dp-db-pgstandby'][0][interface_name]
