---
- name: Get private address for node
  set_fact:
    local_address: '{{ hostvars[inventory_hostname][interface_name].ipv4.address }}'

- name: Get private address for node on AWS
  set_fact:
    local_address: '{{ ansible_ec2_local_ipv4 }}'
  when: "{{ ansible_bios_version is defined and ansible_bios_version | search('amazon') and ansible_ec2_local_ipv4 is defined }}"

- name: Cache local address for node
  cache:
    key: 'local_address'
    value: '{{ local_address }}'
