---
- block:
  - name: Update cache with normalized name for private address
    cache:
      key: 'local_address'
      value: '{{ hostvars[inventory_hostname][interface_name].ipv4.address }}'

  rescue:
    - name: Normalized name for private address was not found, trying alternative
      cache:
        key: 'local_address'
        value: "{{ hostvars[inventory_hostname]['ansible_default_ipv4'].address }}"


- block:

  - name: Update cache with missing private ip on AWS
    ec2_facts:
    when: ansible_ec2_local_ipv4 is not defined

  - name: Update cache with normalized name for private address on AWS
    cache:
      key: 'local_address'
      value: '{{ ansible_ec2_local_ipv4 }}'
    when: ansible_ec2_local_ipv4 is defined

  when: ansible_bios_version is defined and ansible_bios_version | search('amazon')

