---
- block:
  - name: Normalized name for management server local ip if on dc1
    cache:
      key: 'local_mgmt_ip'
      value: "{{ hostvars[groups['dc1-ms'][0]][interface_name].ipv4.address }}"
    when: groups['dc1'] is defined and groups['dc1-ms'] is defined and inventory_hostname in groups['dc1']

  - name: Normalized name for management server local ip if on dc2
    cache:
      key: 'local_mgmt_ip'
      value: "{{ hostvars[groups['dc2-ms'][0]][interface_name].ipv4.address }}"
    when: groups['dc2'] is defined and groups['dc2-ms'] is defined and inventory_hostname in groups['dc2']

  - name: Normalized name for management server local ip to dc1 if current node is not on dc1 or dc2
    cache:
      key: 'local_mgmt_ip'
      value: "{{ hostvars[groups['dc1-ms'][0]][interface_name].ipv4.address }}"
    when: not (inventory_hostname in groups['dc1']) and not (inventory_hostname in groups['dc2'])
  when: groups['dc1'] is defined or groups['dc1-ms'] is defined
