---
# tasks file for apigee-opdk-setup-default-settings
- name: Setup module
  setup:

- name: Normalized network interface name
  cache:
    key: 'interface_name'
    value: 'ansible_{{ ansible_default_ipv4.interface }}'

- include_tasks: private_address.yml

- include_tasks: public_address.yml

- include_tasks: local_mgmt_ip.yml

- include_tasks: ldap.yml

- include_tasks: public_mgmt_ip.yml

- include_tasks: region.yml

- include_tasks: cache.yml

- include_tasks: postgres.yml

- include_tasks: devportal_postgres.yml
