---
# tasks file for apigee-opdk-setup-default-settings
- name: Normalized network interface name
  cache:
    key: 'interface_name'
    value: 'ansible_{{ ansible_default_ipv4.interface }}'
  when: ansible_os_family | lower in ['centos', 'oraclelinux', 'redhat']

- include_tasks: private_address.yml

- include_tasks: public_address.yml

- include_tasks: local_mgmt_ip.yml

- include_tasks: public_mgmt_ip.yml

- include_tasks: region.yml

- include_tasks: update_cache.yml

- include_tasks: postgres.yml


