---
# tasks file for apigee-opdk-setup-default-settings
- include_tasks: network-interface-name.yml

- include_tasks: local_address.yml

- include_tasks: public_address.yml

- include_tasks: local_mgmt_ip.yml

- include_tasks: public_mgmt_ip.yml

- include_tasks: update_cache.yml

- include_tasks: postgres.yml
