---
- name: Normal interface name for redhat family
  set_fact:
    interface_name: 'ansible_eth0'
  when: ansible_os_family | lower == 'redhat' or ansible_os_family | lower == 'centos' or ansible_distribution | lower == 'oraclelinux'

- name: Capture interface Name if running an EL on Virtualbox
  set_fact:
    interface_name: "ansible_eth1"
  when: ansible_bios_version | lower | search('virtualbox') and (ansible_os_family | lower == 'redhat'  or ansible_os_family | lower == 'centos' or ansible_os_family | lower == 'darwin' or ansible_distribution | lower == 'oraclelinux')

- name: Capture Interface Name if running Oracle Linux 7 on Virtualbox
  set_fact:
    interface_name: "ansible_enp0s8"
  when: ansible_bios_version | lower | search('virtualbox') and ansible_distribution | lower | search('oraclelinux') and ansible_distribution_version | version_compare('6', '>')

- name: Capture Interface Name if running Oracle Linux 6 on Virtualbox
  set_fact:
    interface_name: "ansible_eth1"
  when: ansible_bios_version | lower | search('virtualbox') and ansible_distribution_major_version | version_compare('6', '==') and ansible_distribution | lower == 'oraclelinux'

- name: Capture Interface Name if running Oracle Linux 7
  set_fact:
    interface_name: "ansible_enp0s3"
  when: not ansible_bios_version | lower | search('virtualbox') and ansible_distribution_major_version == '7' and ansible_distribution | lower == 'oraclelinux'

- name: Capture Interface Name if running Oracle Linux 6
  set_fact:
    interface_name: "ansible_eth0"
  when: not ansible_bios_version | lower | search('virtualbox') and ansible_distribution_major_version == '6' and ansible_distribution | lower == 'oraclelinux'

- name: Cache interface name for node
  cache:
    key: 'interface_name'
    value: '{{ interface_name | str}}'

