---
- name: Normalized name for management server public ip on dc-1
  set_fact:
    cacheable: yes
    public_mgmt_ip: "{{ groups['dc_1_ms'][0] }}"
  when: groups['dc-1'] is defined and groups['dc_1_ms'] is defined and inventory_hostname in groups['dc-1']

- name: Normalized name for management server public ip  on dc-2
  set_fact:
    cacheable: yes
    public_mgmt_ip: "{{ groups['dc_2_ms'][0] }}"
  when: groups['dc-2'] is defined and groups['dc_2_ms'] is defined and inventory_hostname in groups['dc-2']

- name: Normalized name for management server public ip to dc-1 if current node is not in dc-1 or dc-2
  set_fact:
    cacheable: yes
    public_mgmt_ip: "{{ groups['dc_1_ms'][0] }}"
  when: groups['dc-1'] is defined and groups['dc_1_ms'] is defined and inventory_hostname in groups['dc-1']
