---

- name: Get public address for node
  set_fact:
    public_address: '{{ inventory_hostname }}'

- name: Get public address for node on AWS
  set_fact:
    public_address: '{{ ansible_ec2_public_ipv4 }}'
  when: "{{ ansible_bios_version | search('amazon') and ansible_ec2_public_ipv4 is defined}}"

- name: Cache public address for node
  cache:
    key: 'public_address'
    value: '{{ inventory_hostname }}'
