---
- block:
  - name: Get local management server address if on dc-1
    cache:
      key: 'public_mgmt_ip'
      value: "{{ groups['dc-1-ms'][0] }}"
    when: groups['dc-1-ms'] is defined

  - name: Get local management server address if on dc-2
    cache:
      key: 'public_mgmt_ip'
      value: "{{ groups['dc-2-ms'][0] }}"
    when: groups['dc-2'] is defined and groups['dc-2-ms'] is defined and inventory_hostname in groups['dc-2']

  - name: Fail playbook if local_mgmt_ip cannot be obtained
    fail:
      msg: "Unable to define public_mgmt_ip; likely because of missing dc-1 or dc-2 group in inventory"
    when: public_mgmt_ip is not defined

  when: public_mgmt_ip is not defined
