---
- block:

  - name: OPDK ms server self
    opdk_server_self:
      server_type: 'ms'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'

  when: inventory_hostname in groups['ms']

- block:

  - name: OPDK mp server self
    opdk_server_self:
      server_type: 'mp'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'

  - name: OPDK router server self
    opdk_server_self:
      server_type: 'router'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'

  when: inventory_hostname in groups['rmp']

- block:

  - name: OPDK qs server self
    opdk_server_self:
      server_type: 'qs'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'

  when: inventory_hostname in groups['qpid']

- block:

  - name: OPDK ps server self
    opdk_server_self:
      server_type: 'ps'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'

  when: inventory_hostname in groups['pg']

