---
- name: Update cache with manual_response_file if provided
  cache:
    key: 'manual_response_file'
    value: '{{ manual_response_file }}'
  when: manual_response_file is defined

- name: Update cache with key and value
  cache:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: "jdk_version", value: "{{ jdk_version }}" }
  - { key: "apigeerepobasepath", value: "{{ apigeerepobasepath }}" }
  - { key: 'java_home', value: '{{ java_home }}' }
  - { key: 'opdk_user_name', value: '{{ opdk_user_name }}' }
  - { key: 'opdk_group_name', value: '{{ opdk_group_name }}' }
  - { key: 'opdk_user_email', value: '{{ opdk_user_email }}' }
  - { key: 'opdk_user_pass', value: '{{ opdk_user_pass }}' }
  - { key: 'opdk_user_home', value: '{{ opdk_user_home }}' }
  - { key: 'admin_user', value: '{{ admin_user }}' }
  - { key: 'opdk_version', value: '{{ opdk_version }}' }
  - { key: 'apigee_mirror_version', value: '{{ apigee_mirror_version }}' }
  - { key: 'opdk_installer_path', value: '{{ opdk_installer_path }}' }
  - { key: 'opdk_portal_installation_config_file', value: '{{ opdk_portal_installation_config_file }}' }
  - { key: 'apigee_data_backup_archive_name', value: '{{ apigee_data_backup_archive_name }}' }
  - { key: 'apigee_archive_storage_folder', value: '{{ apigee_archive_storage_folder }}' }
  - { key: 'apigee_installation_home', value: '{{ apigee_installation_home }}' }
  - { key: 'pg_user', value: '{{ pg_user }}' }
  - { key: 'pg_pass', value: '{{ pg_pass }}' }
  - { key: 'apigee_service', value: '{{ apigee_service }}' }
  - { key: 'nodetool', value: '{{ nodetool }}' }
  - { key: 'cqlsh', value: '{{ cqlsh }}' }
  - { key: 'apigee_setup', value: '{{ apigee_setup }}' }
  - { key: 'apigee_update', value: '{{ apigee_update }}' }
  - { key: 'apigee_all', value: '{{ apigee_all }}' }
  - { key: 'opdk_license_target_file_path', value: "{{ opdk_license_target_file_path }}" }
  - { key: 'local_apigee_path', value: "{{ local_apigee_path }}" }
  - { key: 'opdk_license_source_file_name', value: "{{ opdk_license_source_file_name }}" }
  - { key: 'opdk_installation_config_file', value: "{{ opdk_installation_config_file }}" }
  - { key: 'apigee_postgresql_data_dir', value: "{{ apigee_postgresql_data_dir }}" }
  - { key: 'apigee_validate_config_file', value: "{{ apigee_validate_config_file }}" }
  - { key: 'default_apigee_repo_user', value: '{{ default_apigee_repo_user }}' }
  - { key: 'default_apigee_repo_password', value: '{{ default_apigee_repo_password}}' }
  - { key: 'default_apigee_repo_uri', value: '{{ default_apigee_repo_uri }}' }
  - { key: 'default_apigee_repo_protocol', value: '{{ default_apigee_repo_protocol }}' }
  - { key: 'default_apigee_repo_url', value: '{{ default_apigee_repo_url }}' }
  - { key: 'copy_archive', value: '{{ copy_archive }}' }
  - { key: 'apigee_archive_name', value: '{{ apigee_archive_name }}' }
  - { key: 'mp_pod', value: '{{ mp_pod }}' }
  - { key: 'opdk_ldap_type', value: '{{ opdk_ldap_type }}'}
  - { key: 'opdk_ldap_remote_host', value: '{{ opdk_ldap_remote_host }}' }
  - { key: 'opdk_ldap_pass', value: '{{ opdk_ldap_pass }}' }
  - { key: 'opdk_enable_ax', value: '{{ opdk_enable_ax }}' }
  - { key: 'default_mp_pod', value: '{{ default_mp_pod }}' }
  - { key: 'opdk_use_zk_cluster', value: '{{ opdk_use_zk_cluster }}' }
  - { key: 'opdk_cass_clustername', value: '{{ opdk_cass_clustername }}' }
  - { key: 'opdk_use_cass_cluster', value: '{{ opdk_use_cass_cluster }}' }
  - { key: 'opdk_smtp_skip', value: '{{ opdk_smtp_skip }}' }
  - { key: 'opdk_smtp_host', value: '{{ opdk_smtp_host }}' }
  - { key: 'opdk_smtp_port', value: '{{ opdk_smtp_port }}' }
  - { key: 'opdk_smtp_user', value: '{{ opdk_smtp_user }}'}
  - { key: 'opdk_smtp_password', value: '{{ opdk_smtp_password }}' }
  - { key: 'opdk_smtp_ssl', value: '{{ opdk_smtp_ssl }}' }
  - { key: "psql", value: "{{ psql }}" }
  - { key: 'opdk_cass_auth', value: '{{ opdk_cass_auth }}' }
  - { key: 'opdk_cass_password', value: '{{ opdk_cass_password }}' }
  - { key: 'opdk_cass_username', value: '{{ opdk_cass_username }}' }
  - { key: 'consumer_group', value: '{{ consumer_group }}' }
  - { key: 'ldap_data_port', value: '{{ ldap_data_port }}' }
  - { key: 'edge_proxy_port', value: '{{ edge_proxy_port }}' }
  - { key: 'ui_http_port', value: '{{ ui_http_port }}' }
  - { key: 'pg_ext_mgmt_port', value: '{{ pg_ext_mgmt_port }}' }
  - { key: 'pg_db_port', value: '{{ pg_db_port }}' }
  - { key: 'pg_int_mgmt_port', value: '{{ pg_int_mgmt_port }}' }
  - { key: 'pg_jmx_port', value: '{{ pg_jmx_port }}' }
  - { key: 'qpid_ext_mgmt_port', value: '{{ qpid_ext_mgmt_port }}' }
  - { key: 'router_int_mgmt_port', value: '{{ router_int_mgmt_port }}' }
  - { key: 'qpid_jmx_port', value: '{{ qpid_jmx_port }}' }
  - { key: 'qpid_int_mgmt_port', value: '{{ qpid_int_mgmt_port }}' }
  - { key: 'qpid_messaging_port', value: '{{ qpid_messaging_port }}' }
  - { key: 'router_ext_mgmt_port', value: '{{ router_ext_mgmt_port }}' }
  - { key: 'router_jmx_port', value: '{{ router_jmx_port }}' }
  - { key: 'ms_ext_mgmt_port', value: '{{ ms_ext_mgmt_port }}' }
  - { key: 'ms_jmx_port', value: '{{ ms_jmx_port }}' }
  - { key: 'mp_router_port', value: '{{ mp_router_port }}' }
  - { key: 'mp_jmx_port', value: '{{ mp_jmx_port }}' }
  - { key: 'mp_ext_mgmt_port', value: '{{ mp_ext_mgmt_port }}' }
  - { key: 'mp_int_mgmt_port', value: '{{ mp_int_mgmt_port }}' }
  - { key: 'zk_voter_port', value: '{{ zk_voter_port }}' }
  - { key: 'zk_leader_port', value: '{{ zk_leader_port }}' }
  - { key: 'zk_data_port', value: '{{ zk_data_port }}' }
  - { key: 'cassandra_ssl_gossip_port', value: '{{ cassandra_ssl_gossip_port }}' }
  - { key: 'cassandra_non_ssl_gossip_port', value: '{{ cassandra_non_ssl_gossip_port }}' }
  - { key: 'cassandra_cql_native_port', value: '{{ cassandra_cql_native_port }}' }
  - { key: 'cassandra_thrift_client_port', value: '{{ cassandra_thrift_client_port }}' }
  - { key: 'cassandra_jmx_port', value: '{{ cassandra_jmx_port }}' }
  - { key: 'apigee_provision_dir', value: '{{ apigee_provision_dir }}' }
  - { key: 'env_name', value: '{{ env_name }}' }
  - { key: 'ax_group', value: '{{ ax_group }}' }
  - { key: 'virtual_host_name', value: '{{ virtual_host_name }}' }
  - { key: 'virtual_host_port', value: '{{ virtual_host_port }}' }
  - { key: 'last_name', value: '{{ last_name }}' }
  - { key: 'first_name', value: '{{ first_name }}' }
  - { key: 'new_user', value: '{{ new_user }}' }
  - { key: 'onboarding_config', value: '{{ onboarding_config }}' }
  - { key: 'onboarding_config_file_path', value: '{{ onboarding_config_file_path }}' }
  - { key: 'qpid_ext_mgmt_port', value: '{{ qpid_ext_mgmt_port }}' }
  - { key: 'ms_ext_mgmt_port', value: '{{ ms_ext_mgmt_port }}' }
  - { key: 'org_name', value: '{{ org_name }}' }
  - { key: 'opdk_bind_on_all_interfaces', value: '{{ opdk_bind_on_all_interfaces }}' }
  - { key: 'opdk_smtp_mail_from', value: '{{ opdk_smtp_mail_from }}' }
  - { key: 'enable_system_check', value: '{{ enable_system_check }}' }
  - { key: 'local_apigee_secure', value: '{{ local_apigee_secure }}' }
  - { key: 'drupal_pg_user', value: '{{ opdk_user_name }}' }
  - { key: 'drupal_pg_password', value: '{{ opdk_user_pass }}' }
  - { key: 'dp_admin_firstname', value: "firstname" }
  - { key: 'dp_admin_lastname', value: "lastname" }
  - { key: 'dp_admin_username', value: "dp_admin" }
  - { key: 'dp_admin_pwd', value: "{{ opdk_user_pass }}" }
  - { key: 'dp_admin_email', value: "{{ opdk_user_email }}" }
  - { key: 'dp_devadmin_user', value: "{{ opdk_user_name }}" }
  - { key: 'dp_devadmin_pwd', value: "{{ opdk_user_pass }}" }
  - { key: 'opdk_portal_db_config_file', value: "{{ opdk_portal_db_config_file }}" }
