---
- name: Update cache with jdk_version
  cache:
    key: 'jdk_version'
    value: '{{ jdk_version }}'

- name: Update cache with java_home
  cache:
    key: 'java_home'
    value: '{{ java_home }}'

- name: Update cache with opdk_user_name
  cache:
    key: 'opdk_user_name'
    value: '{{ opdk_user_name }}'

- name: Update cache with opdk_group_name
  cache:
    key: 'opdk_group_name'
    value: '{{ opdk_group_name }}'

- name: Update cache with opdk_email_name
  cache:
    key: 'opdk_user_email'
    value: '{{ opdk_user_email }}'

- name: Update cache with opdk_user_password
  cache:
    key: 'opdk_user_pass'
    value: '{{ opdk_user_pass }}'

- name: Update cache with opdk_user_home
  cache:
    key: 'opdk_user_home'
    value: '{{ opdk_user_home }}'

- name: Update cache with admin_user
  cache:
    key: 'admin_user'
    value: '{{ admin_user }}'

- name: Update cache with opdk_version
  cache:
    key: 'opdk_version'
    value: '{{ opdk_version }}'

- name: Update cache with apigee_mirror_version
  cache:
    key: 'apigee_mirror_version'
    value: '{{ apigee_mirror_version }}'

- name: Update cache with opdk_installer_path path
  cache:
    key: 'opdk_installer_path'
    value: '{{ opdk_installer_path }}'

- name: Update cache with apigee_data_backup_archive_name
  cache:
    key: 'apigee_data_backup_archive_name'
    value: '{{ apigee_data_backup_archive_name }}'

- name: Update cache with apigee_archive_storage_folder path
  cache:
    key: 'apigee_archive_storage_folder'
    value: '{{ apigee_archive_storage_folder }}'

- name: Update cache with apigee_installation_home path
  cache:
    key: 'apigee_installation_home'
    value: '{{ apigee_installation_home }}'

- name: Update cache with pg_user path
  cache:
    key: 'pg_user'
    value: '{{ pg_user }}'

- name: Update cache with pg_pass path
  cache:
    key: 'pg_pass'
    value: '{{ pg_pass }}'

- name: Update cache with apigee_service path
  cache:
    key: 'apigee_service'
    value: '{{ apigee_service }}'

- name: Update cache with nodetool path
  cache:
    key: 'nodetool'
    value: '{{ nodetool }}'

- name: Update cache with cqlsh path
  cache:
    key: 'cqlsh'
    value: '{{ cqlsh }}'

- name: Update cache with apigee_setup path
  cache:
    key: 'apigee_setup'
    value: '{{ apigee_setup }}'

- name: Update cache with apigee_update path
  cache:
    key: 'apigee_update'
    value: '{{ apigee_update }}'

- name: Update cache with apigee_all path
  cache:
    key: 'apigee_all'
    value: '{{ apigee_all }}'

- name: Update cache with opdk_license_target_file_path path
  cache:
    key: 'opdk_license_target_file_path'
    value: "{{ opdk_license_target_file_path }}"

- name: Update cache with local_resource_path path
  cache:
    key: 'local_resource_path'
    value: "{{ local_resource_path }}"

- name: Update cache with opdk_license_source_file_name path
  cache:
    key: 'opdk_license_source_file_name'
    value: "{{ opdk_license_source_file_name }}"

- name: Update cache with opdk_installation_config_file path
  cache:
    key: 'opdk_installation_config_file'
    value: "{{ opdk_installation_config_file }}"

- name: Update cache with apigee_postgresql_data_dir path
  cache:
    key: 'apigee_postgresql_data_dir'
    value: "{{ apigee_postgresql_data_dir }}"

- name: Update cache with provided_response_file path
  cache:
    key: 'provided_response_file'
    value: "{{ provided_response_file }}"

- name: Update cache with apigee_validate_config_file path
  cache:
    key: 'apigee_validate_config_file'
    value: "{{ apigee_validate_config_file }}"

- name: Update cache with apigee_repo_user path
  cache:
    key: 'apigee_repo_user'
    value: '{{ apigee_repo_user }}'

- name: Update cache with apigee_repo_password path
  cache:
    key: 'apigee_repo_password'
    value: '{{ apigee_repo_password }}'

- name: Update cache with apigee_repo_uri path
  cache:
    key: 'apigee_repo_uri'
    value: '{{ apigee_repo_uri }}'

- name: Update cache with apigee_repo_protocol path
  cache:
    key: 'apigee_repo_protocol'
    value: '{{ apigee_repo_protocol }}'

- name: Update cache with apigee_repo_url path
  cache:
    key: 'apigee_repo_url'
    value: '{{ apigee_repo_url }}'

- name: Update cache with copy_archive path
  cache:
    key: 'copy_archive'
    value: '{{ copy_archive }}'

- name: Update cache with archive_folder path
  cache:
    key: 'archive_folder'
    value: '{{ archive_folder }}'

- name: Update cache with archive_name path
  cache:
    key: 'archive_name'
    value: '{{ archive_name }}'

- name: Update cache with archive_path path
  cache:
    key: 'archive_path'
    value: '{{ archive_path }}'

- name: Update cache with mp_pod path
  cache:
    key: 'mp_pod'
    value: '{{ mp_pod }}'

